
columns:
  - elevation: int
  - aspect: int
  - slope: int
  - horizontal_distance_to_hydrology: int
  - Vertical_Distance_To_Hydrology: int
  - Horizontal_Distance_To_Roadways: int
  - Horizontal_Distance_To_Fire_Points: int
  - wilderness_area1: int
  - wilderness_area2: int
  - wilderness_area3: int
  - wilderness_area4: int
  - soil_type_1: int
  - soil_type_2: int
  - soil_type_3: int
  - soil_type_4: int
  - soil_type_5: int
  - soil_type_6: int
  - soil_type_7: int
  - soil_type_8: int
  - soil_type_9: int
  - soil_type_10: int
  - soil_type_11: int
  - soil_type_12: int
  - soil_type_13: int
  - soil_type_14: int
  - soil_type_15: int
  - soil_type_16: int
  - soil_type_17: int
  - soil_type_18: int
  - soil_type_19: int
  - soil_type_20: int
  - soil_type_21: int
  - soil_type_22: int
  - soil_type_23: int
  - soil_type_24: int
  - soil_type_25: int
  - soil_type_26: int
  - soil_type_27: int
  - soil_type_28: int
  - soil_type_29: int
  - soil_type_30: int
  - soil_type_31: int
  - soil_type_32: int
  - soil_type_33: int
  - soil_type_34: int
  - soil_type_35: int
  - soil_type_36: int
  - soil_type_37: int
  - soil_type_38: int
  - soil_type_39: int
  - soil_type_40: int
  - Cover_Type: category


numerical_columns:
  - elevation: int
  - aspect: int
  - slope: int
  - horizontal_distance_to_hydrology: int
  - Vertical_Distance_To_Hydrology: int
  - Horizontal_Distance_To_Roadways: int
  - Horizontal_Distance_To_Fire_Points: int
  - wilderness_area1: int
  - wilderness_area2: int
  - wilderness_area3: int
  - wilderness_area4: int
  - soil_type_1: int
  - soil_type_2: int
  - soil_type_3: int
  - soil_type_4: int
  - soil_type_5: int
  - soil_type_6: int
  - soil_type_7: int
  - soil_type_8: int
  - soil_type_9: int
  - soil_type_10: int
  - soil_type_11: int
  - soil_type_12: int
  - soil_type_13: int
  - soil_type_14: int
  - soil_type_15: int
  - soil_type_16: int
  - soil_type_17: int
  - soil_type_18: int
  - soil_type_19: int
  - soil_type_20: int
  - soil_type_21: int
  - soil_type_22: int
  - soil_type_23: int
  - soil_type_24: int
  - soil_type_25: int
  - soil_type_26: int
  - soil_type_27: int
  - soil_type_28: int
  - soil_type_29: int
  - soil_type_30: int
  - soil_type_31: int
  - soil_type_32: int
  - soil_type_33: int
  - soil_type_34: int
  - soil_type_35: int
  - soil_type_36: int
  - soil_type_37: int
  - soil_type_38: int
  - soil_type_39: int
  - soil_type_40: int

categorical_columns:
  - Cover_Type

target_column: Cover_Type

drop_columns:
  - Soil_Type_7
  - Soil_Type_8
  - Soil_Type_15
  - Soil_Type_36
