
columns:
  - elevation: int
  - aspect: int
  - slope: int
  - horizontal_distance_to_hydrology: int
  - Vertical_Distance_To_Hydrology: int
  - Horizontal_Distance_To_Roadways: int
  - Horizontal_Distance_To_Fire_Points: int
  - wilderness_area1: int
  - wilderness_area2: int
  - wilderness_area3: int
  - wilderness_area4: int
  - soil_type1: int
  - soil_type2: int
  - soil_type3: int
  - soil_type4: int
  - soil_type5: int
  - soil_type6: int
  - soil_type7: int
  - soil_type8: int
  - soil_type9: int
  - soil_type10: int
  - soil_type11: int
  - soil_type12: int
  - soil_type13: int
  - soil_type14: int
  - soil_type15: int
  - soil_type16: int
  - soil_type17: int
  - soil_type18: int
  - soil_type19: int
  - soil_type20: int
  - soil_type21: int
  - soil_type22: int
  - soil_type23: int
  - soil_type24: int
  - soil_type25: int
  - soil_type26: int
  - soil_type27: int
  - soil_type28: int
  - soil_type29: int
  - soil_type30: int
  - soil_type31: int
  - soil_type32: int
  - soil_type33: int
  - soil_type34: int
  - soil_type35: int
  - soil_type36: int
  - soil_type37: int
  - soil_type38: int
  - soil_type39: int
  - soil_type40: int
  - Cover_Type: category


numerical_columns:
  - elevation: int
  - aspect: int
  - slope: int
  - horizontal_distance_to_hydrology: int
  - Vertical_Distance_To_Hydrology: int
  - Horizontal_Distance_To_Roadways: int
  - Horizontal_Distance_To_Fire_Points: int
  - wilderness_area1: int
  - wilderness_area2: int
  - wilderness_area3: int
  - wilderness_area4: int
  - soil_type1: int
  - soil_type2: int
  - soil_type3: int
  - soil_type4: int
  - soil_type5: int
  - soil_type6: int
  - soil_type7: int
  - soil_type8: int
  - soil_type9: int
  - soil_type10: int
  - soil_type11: int
  - soil_type12: int
  - soil_type13: int
  - soil_type14: int
  - soil_type15: int
  - soil_type16: int
  - soil_type17: int
  - soil_type18: int
  - soil_type19: int
  - soil_type20: int
  - soil_type21: int
  - soil_type22: int
  - soil_type23: int
  - soil_type24: int
  - soil_type25: int
  - soil_type26: int
  - soil_type27: int
  - soil_type28: int
  - soil_type29: int
  - soil_type30: int
  - soil_type31: int
  - soil_type32: int
  - soil_type33: int
  - soil_type34: int
  - soil_type35: int
  - soil_type36: int
  - soil_type37: int
  - soil_type38: int
  - soil_type39: int
  - soil_type40: int

categorical_columns:
  - Cover_Type

target_column: Cover_Type

drop_columns:
  - Soil_Type7
  - Soil_Type8
  - Soil_Type15
  - Soil_Type36
