
columns:
  - Elevation: int
  - Aspect: int
  - Slope: int
  - Horizontal_Distance_To_Hydrology: int
  - Vertical_Distance_To_Hydrology: int
  - Horizontal_Distance_To_Roadways: int
  - Hillshade_9am: int
  - Hillshade_Noon: int
  - Hillshade_3pm: int
  - Horizontal_Distance_To_Fire_Points: int
  - Wilderness_Area1: int
  - Wilderness_Area2: int
  - Wilderness_Area3: int
  - Wilderness_Area4: int
  - Soil_Type1: int
  - Soil_Type2: int
  - Soil_Type3: int
  - Soil_Type4: int
  - Soil_Type5: int
  - Soil_Type6: int
  - Soil_Type7: int
  - Soil_Type8: int
  - Soil_Type9: int
  - Soil_Type10: int
  - Soil_Type11: int
  - Soil_Type12: int
  - Soil_Type13: int
  - Soil_Type14: int
  - Soil_Type15: int
  - Soil_Type16: int
  - Soil_Type17: int
  - Soil_Type18: int
  - Soil_Type19: int
  - Soil_Type20: int
  - Soil_Type21: int
  - Soil_Type22: int
  - Soil_Type23: int
  - Soil_Type24: int
  - Soil_Type25: int
  - Soil_Type26: int
  - Soil_Type27: int
  - Soil_Type28: int
  - Soil_Type29: int
  - Soil_Type30: int
  - Soil_Type31: int
  - Soil_Type32: int
  - Soil_Type33: int
  - Soil_Type34: int
  - Soil_Type35: int
  - Soil_Type36: int
  - Soil_Type37: int
  - Soil_Type38: int
  - Soil_Type39: int
  - Soil_Type40: int
  - Cover_Type: category


numerical_columns:
  - Elevation
  - Aspect
  - Slope
  - Horizontal_Distance_To_Hydrology
  - Vertical_Distance_To_Hydrology
  - Horizontal_Distance_To_Roadways
  - Hillshade_9am
  - Hillshade_Noon
  - Hillshade_3pm
  - Horizontal_Distance_To_Fire_Points
  - Wilderness_Area1
  - Wilderness_Area2
  - Wilderness_Area3
  - Wilderness_Area4
  - Soil_Type1
  - Soil_Type2
  - Soil_Type3
  - Soil_Type4
  - Soil_Type5
  - Soil_Type6
  - Soil_Type7
  - Soil_Type8
  - Soil_Type9
  - Soil_Type10
  - Soil_Type11
  - Soil_Type12
  - Soil_Type13
  - Soil_Type14
  - Soil_Type15
  - Soil_Type16
  - Soil_Type17
  - Soil_Type18
  - Soil_Type19
  - Soil_Type20
  - Soil_Type21
  - Soil_Type22
  - Soil_Type23
  - Soil_Type24
  - Soil_Type25
  - Soil_Type26
  - Soil_Type27
  - Soil_Type28
  - Soil_Type29
  - Soil_Type30
  - Soil_Type31
  - Soil_Type32
  - Soil_Type33
  - Soil_Type34
  - Soil_Type35
  - Soil_Type36
  - Soil_Type37
  - Soil_Type38
  - Soil_Type39
  - Soil_Type40

categorical_columns:
  - Cover_Type

target_column: Cover_Type

drop_columns:
  - Soil_Type7
  - Soil_Type8
  - Soil_Type15
  - Soil_Type36
